/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '1.0.51',
  gitHash: '9fe5693',
  gitBranch: 'main',
  buildTime: '2026-02-14T18:45:14Z',
  nodeVersion: 'v25.2.1',
  isDirty: true,
} as const;

export type BuildInfo = typeof BUILD_INFO;
