/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '1.0.0',
  gitHash: '242793f',
  gitBranch: 'main',
  buildTime: '2026-01-07T16:44:27Z',
  nodeVersion: 'v25.2.1',
  isDirty: true,
} as const;

export type BuildInfo = typeof BUILD_INFO;
