/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '1.0.2',
  gitHash: '5d5ff81',
  gitBranch: 'preview',
  buildTime: '2026-01-22T18:23:52Z',
  nodeVersion: 'v25.2.1',
  isDirty: false,
} as const;

export type BuildInfo = typeof BUILD_INFO;
