#!/bin/bash

# Generate build metadata for Izzie2
# Creates src/lib/build-info.ts with current build information

set -e

# Get build metadata
VERSION=$(node -p "require('./package.json').version")
GIT_HASH=$(git rev-parse --short HEAD)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
NODE_VERSION=$(node --version)

# Get git status
if [[ -n $(git status -s) ]]; then
  GIT_DIRTY=true
else
  GIT_DIRTY=false
fi

# Create build-info.ts
cat > src/lib/build-info.ts << EOF
/**
 * Build information generated at build time
 * DO NOT EDIT - This file is automatically generated by scripts/build-info.sh
 */

export const BUILD_INFO = {
  version: '${VERSION}',
  gitHash: '${GIT_HASH}',
  gitBranch: '${GIT_BRANCH}',
  buildTime: '${BUILD_TIME}',
  nodeVersion: '${NODE_VERSION}',
  isDirty: ${GIT_DIRTY},
} as const;

export type BuildInfo = typeof BUILD_INFO;
EOF

echo "✓ Build info generated: src/lib/build-info.ts"
echo "  Version: ${VERSION}"
echo "  Git Hash: ${GIT_HASH}"
echo "  Branch: ${GIT_BRANCH}"
echo "  Build Time: ${BUILD_TIME}"
